[Variables]
;@About | Name Settings | Icon [\xE713]
;@Topic | Name Visualizer Settings | Icon [\xF61F]
;@ | Name Group[#s_VarGroup]

;Integer | Name X
XG[#s_VarGroup]=0

;Integer | Name Y
YG[#s_VarGroup]=0

;Integer | Name Starting Index | Description Audio measure start index
MeasureStartG[#s_VarGroup]=1

;Integer | Name BarCount
BarCountG[#s_VarGroup]=25

;Integer | Name Height
HeightG[#s_VarGroup]=160

;?Integer | Name Width
WidthG[#s_VarGroup]=10

;?Integer | Name Gap
GapG[#s_VarGroup]=4

;?Integer | Name StrokeWidth
StrokeWidthG[#s_VarGroup]=0

;?Integer | Name Rounding
RoundingG[#s_VarGroup]=2

;?Toggle | Name X-Flip | Description Flips the visualizer wrt Y-axis
XFlipG[#s_VarGroup]=0

;?String | Name Angle
AngleG[#s_VarGroup]=0

;?Integer | Name Minimum Height
MinimumHeightG[#s_VarGroup]=10

ImageNameG[#s_VarGroup]=

;?Color | Name Color
ColorG[#s_VarGroup]=150, 200, 250

;?Gradient | Name Gradient | See Rainmeter meter Docs for more info on defining gradients
GradientG[#s_VarGroup]=180 | 249, 116, 31;0.0 | 242, 75, 59;1.0
GradientBoolG[#s_VarGroup]=1